### ISSUE TITLE
Should restart docker daemon when docker service options are modified

### ISSUE THREAD

**Issue by jperville** [someara/chef-docker#423]
Modifying attributes of the `docker_service` does not trigger restart of the docker service (it should).

For example, if my recipe had the following code:
```ruby
docker_service 'default' do
  action [:create, :start]
end
```

Then I change it to:
```ruby
docker_service 'default' do
  storage_driver 'overlay' # or whatever
  action [:create, :start]
end
```

Then the docker service is not restarted after converging `docker_service[default]`.

The correct behavior should be that every time the content of `template[/etc/default/docker]` is modified then the docker service should also be restarted.

This issue is similar to #420.

**Comment by someara** [comment]
This one is going to be a doozey... I'm still shaking the last bugs out from enabling this on docker_container =)

**Comment by someara** [comment]
okay I've started this as of 1.0.35.

We should continuously deliver this feature as it develops, rather than try and do it all in one big feature like docker_container. That way it can happen one property at a time.

https://github.com/bflad/chef-docker/blob/c524a9e87133bf1bcdebc53a530de349926c6bd8/libraries/provider_docker_service.rb#L23

The general pattern is going to be exactly the same as with the override stuff in docker_container. That is, there is no way to determine if a current setting was set by a previous chef-client run, or by the docker service selecting defaults.

The two options right now are:
a) treat them as unmanaged when removing a resource property, or
b) reimplement the defaults selection logic from Docker in this cookbook.

Let's start with A.

-s

**Comment by someara** [comment]
PS - Changing the storage driver on a previously running docker_service results in a rather spectacular explosion... which is a Docker problem, not a Chef problem =)

**Comment by someara** [comment]
I don't know if you want to leave this ticket open and track everything here, or close it and create one for each property as they're added

**Comment by jperville** [comment]
You can leave the ticket open and track everything here.

**Comment by agarat** [comment]
I don't think the docker service should be restarted when modifying the service attributes. I'm currently using this cookbook in a production environment, Docker service restarts should be controlled to avoid data loss or services downtime. 
Perhaps if this feature gets implemented there should be an option to avoid restarting the service automatically.

**Comment by bflad** [comment]
Yes, please make it configurable if it becomes an option.

**Comment by someara** [comment]
noted!

**Comment by someara** [comment]
Hello!

This now works via template repairs notifying the docker_service_manager.
The `docker_service` :auto_restart  property defaults to false for safety.

-s
